### PR TITLE
Add changelog in readme and increase version number

### PR DESCRIPTION
**Pull request by JohanLorenzo**
Hi @kzjeef !

Thank you for making this package available on Pypi. I'd like to use a Python-3 compatible version of this library (thanks for the changes @DariuszAniszewski). Would it be possible to push a new version to Pypi?

### CODE REVIEW

**Comment by kzjeef** [comment]
Sure, but I don't understand this PR, I think this RP don't include Python-3 compatible patch , right ?

If it's possible , can you merge the changes and resubmit a RP ?

I can do the merge and update pypip task.

**Comment by JohanLorenzo** [comment]
Thanks for your rapid answer 😃 Python 3 was made compatible in #1, wasn't it?

**Comment by kzjeef** [comment]
Oh, my bad. 

I will update the package soon.

**Comment by kzjeef** [comment]
it's done.

**Pull request merged**
